# Generated by Django 5.2.2 on 2025-06-09 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=200)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento'), ('COMERCIAL', 'Comercial'), ('TERRENO', 'Terreno')], max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quartos', models.IntegerField()),
                ('banheiros', models.IntegerField()),
                ('vagas_garagem', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('VENDIDO', 'Vendido'), ('ALUGADO', 'Alugado')], default='DISPONIVEL', max_length=20)),
                ('operacao', models.CharField(choices=[('VENDA', 'Venda'), ('ALUGUEL', 'Aluguel')], max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
