# Generated by Django 5.2.2 on 2025-06-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
