# Generated by Django 5.2.2 on 2025-06-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_corretor',
            field=models.BooleanField(default=False, help_text='Define se o usuário é um corretor', verbose_name='É corretor'),
        ),
    ]
