# Generated by Django 5.2.2 on 2025-06-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_is_corretor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_corretor',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CORRETOR', 'Corretor'), ('CLIENTE', 'Cliente')], help_text='Selecione se é Cliente ou Corretor', max_length=10, verbose_name='Tipo de Usuário'),
        ),
    ]
